### ISSUE TITLE
Update DB_RAW_V3 to DB_CUSTOM_V5

### ISSUE THREAD

**Issue by Itsyuka** [Itsyuka/Altis-Life#4]
Will increase security and decrease the callExtension input.

**Comment by Torndeco** [comment]
Increase Security, 
Ability Remove the SQL Procedures @ startup & have DELETE SQL Queries while server is running without risk of someone dropping the entire Database.

Faster SQL Queries, since SQL Server has SQL Statement already compiled after the first run.
Extra options

Offload Armaserver workload to extension, decrease amount of work armaserver needs todo.

Length of the input is not a feature

**Comment by Itsyuka** [comment]
Again, I can't explain properly, this is why I love your explanations more.
